  list p=16f886		;Identifica el PIC a usar
   #include <P16F886.INC>	;Cabecera que define los registros del MCU

;   Bits de configuración del MCU
; CONFIG1
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_OFF
; CONFIG2
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

    
    	ORG	0
	GOTO	INICIO
	
INICIO
	BSF	STATUS,RP0  ;banco 1
	MOVLW	D'77'
	MOVWF	PR2
	BCF	TRISB,0
	BCF	TRISC,2;RC2 
	BCF	STATUS,RP0	;banco 0
	MOVLW   B'00111110' ;80% MSB
	MOVWF	CCPR1L
	BSF	CCP1CON,5 ; 1 LSB 80%
	BCF	CCP1CON,4 ; 0
	BSF	T2CON,1 ;16 PRESCALER
	BCF	T2CON,0
	BSF	T2CON,2; TMR2 ON
	BSF	CCP1CON,3; 11XX PWM
	BSF	CCP1CON,2
	BSF	CCP1CON,1
	BSF	CCP1CON,0
START
	BSF	PORTB,0
	GOTO	START


	END



